name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Configure GitHub Packages auth
        run: |
          echo "@dot-steward:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Bump versions from tag
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Version from tag: $VERSION"
          bun run release:version -- $VERSION

      - name: Publish packages (bun via turbo)
        run: bun run release:publish
